In [ ]:
import math
import numpy as np
from scipy.stats import norm


class EuropeanCall:

    def call_delta(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        b = math.exp(-risk_free_rate*time_to_expiration)
        x1 = math.log(asset_price/(b*strike_price)) + .5*(asset_volatility*asset_volatility)*time_to_expiration
        x1 = x1/(asset_volatility*(time_to_expiration**.5))
        z1 = norm.cdf(x1)
        return z1

    def call_gamma(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        b = math.exp(-risk_free_rate*time_to_expiration)
        x1 = math.log(asset_price/(b*strike_price)) + .5*(asset_volatility*asset_volatility)*time_to_expiration
        x1 = x1/(asset_volatility*(time_to_expiration**.5))
        z1 = norm.cdf(x1)
        z2 = z1/(asset_price*asset_volatility*math.sqrt(time_to_expiration))
        return z2

    def call_vega(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        b = math.exp(-risk_free_rate*time_to_expiration)
        x1 = math.log(asset_price/(b*strike_price)) + .5*(asset_volatility*asset_volatility)*time_to_expiration
        x1 = x1/(asset_volatility*(time_to_expiration**.5))
        z1 = norm.cdf(x1)
        z2 = asset_price*z1*math.sqrt(time_to_expiration)
        return z2/100

    def call_price(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        b = math.exp(-risk_free_rate*time_to_expiration)
        x1 = math.log(asset_price/(b*strike_price)) + .5*(asset_volatility*asset_volatility)*time_to_expiration
        x1 = x1/(asset_volatility*(time_to_expiration**.5))
        z1 = norm.cdf(x1)
        z1 = z1*asset_price
        x2 = math.log(asset_price/(b*strike_price)) - .5*(asset_volatility*asset_volatility)*time_to_expiration
        x2 = x2/(asset_volatility*(time_to_expiration**.5))
        z2 = norm.cdf(x2)
        z2 = b*strike_price*z2
        return z1 - z2

    def __init__(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        self.asset_price = asset_price
        self.asset_volatility = asset_volatility
        self.strike_price = strike_price
        self.time_to_expiration = time_to_expiration
        self.risk_free_rate = risk_free_rate
        self.price = self.call_price(asset_price, asset_volatility, strike_price, time_to_expiration, risk_free_rate)
        self.delta = self.call_delta(asset_price, asset_volatility, strike_price, time_to_expiration, risk_free_rate)
        self.gamma = self.call_gamma(asset_price, asset_volatility, strike_price, time_to_expiration, risk_free_rate)
        self.vega = self.call_vega(asset_price, asset_volatility, strike_price, time_to_expiration, risk_free_rate)


class EuropeanPut:

    def put_delta(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        b = math.exp(-risk_free_rate*time_to_expiration)
        x1 = math.log(asset_price/(b*strike_price)) + .5*(asset_volatility*asset_volatility)*time_to_expiration
        x1 = x1/(asset_volatility*(time_to_expiration**.5))
        z1 = norm.cdf(x1)
        return z1 - 1

    def put_gamma(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        b = math.exp(-risk_free_rate*time_to_expiration)
        x1 = math.log(asset_price/(b*strike_price)) + .5*(asset_volatility*asset_volatility)*time_to_expiration
        x1 = x1/(asset_volatility*(time_to_expiration**.5))
        z1 = norm.cdf(x1)
        z2 = z1/(asset_price*asset_volatility*math.sqrt(time_to_expiration))
        return z2

    def put_vega(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        b = math.exp(-risk_free_rate*time_to_expiration)
        x1 = math.log(asset_price/(b*strike_price)) + .5*(asset_volatility*asset_volatility)*time_to_expiration
        x1 = x1/(asset_volatility*(time_to_expiration**.5))
        z1 = norm.cdf(x1)
        z2 = asset_price*z1*math.sqrt(time_to_expiration)
        return z2/100

    def put_price(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        b = math.exp(-risk_free_rate*time_to_expiration)
        x1 = math.log((b*strike_price)/asset_price) + .5*(asset_volatility*asset_volatility)*time_to_expiration
        x1 = x1/(asset_volatility*(time_to_expiration**.5))
        z1 = norm.cdf(x1)
        z1 = b*strike_price*z1
        x2 = math.log((b*strike_price)/asset_price) - .5*(asset_volatility*asset_volatility)*time_to_expiration
        x2 = x2/(asset_volatility*(time_to_expiration**.5))
        z2 = norm.cdf(x2)
        z2 = asset_price*z2
        return z1 - z2

    def __init__(
        self, asset_price, asset_volatility, strike_price,
        time_to_expiration, risk_free_rate
            ):
        self.asset_price = asset_price
        self.asset_volatility = asset_volatility
        self.strike_price = strike_price
        self.time_to_expiration = time_to_expiration
        self.risk_free_rate = risk_free_rate
        self.price = self.put_price(asset_price, asset_volatility, strike_price, time_to_expiration, risk_free_rate)
        self.delta = self.put_delta(asset_price, asset_volatility, strike_price, time_to_expiration, risk_free_rate)
        self.gamma = self.put_gamma(asset_price, asset_volatility, strike_price, time_to_expiration, risk_free_rate)
        self.vega = self.put_vega(asset_price, asset_volatility, strike_price, time_to_expiration, risk_free_rate)

randomchoice = EuropeanCall(543, .20, 550, 30/365, .05)
print(randomchoice.delta*-1000) # Delta exposure
print(randomchoice.gamma*-1000) # Gamma exposure
print(randomchoice.vega*-1000)  # Vega exposure
call_a = EuropeanCall(543, .20, 545, 30/365, .05)
print(call_a.delta)       # Option A Delta exposure
print(call_a.gamma)       # Option A Gamma exposure
print(call_a.vega)        # Option A Vega exposure
call_b = EuropeanCall(543, .20, 555, 30/365, .05)
print(call_b.delta)       # Option B Delta exposure
print(call_b.gamma)       # Option B Gamma exposure
print(call_b.vega)        # Option B Vega exposure

# Question is : How can we come up with a certain combination of both call A & Call B to off set the negative -451.0332970484993 exposure to delta, the negative -14.48653713404089 exposure to gamma and the negative -702.1382445098338 vega in our portfolio ? Answer of this question is Linear Algebra.

greeks = np.array([[call_a.gamma, call_b.gamma], [call_a.vega, call_b.vega]]) # Here we represent as a simple linear algebra problem. We creat the greeks matrice.
portfolio_greeks = [[randomchoice.gamma*1000], [randomchoice.vega*1000]]

inv = np.linalg.inv(np.round(greeks, 2)) # we solve by inverting greeks associated with the 2 tradable options, multiplying by the exposure we trying to achieve. This way we can find the weights of the tradable option that will neutraliz both Gamma and Vega
print(inv)

w = np.dot(inv, portfolio_greeks) # Here is the position we need to take (8641.86804927 for option A and -8006.91595494] for option B)
print(w)

print(np.round(np.dot(np.round(greeks, 2), w) - portfolio_greeks))

portfolio_greeks = [[randomchoice.delta*-1000], [randomchoice.gamma*-1000], [randomchoice.vega*-1000]]
greeks = np.array([[call_a.delta, call_b.delta], [call_a.gamma, call_b.gamma], [call_a.vega, call_b.vega]])
print(np.round(np.dot(np.round(greeks, 2), w) + portfolio_greeks)) # # here we check that we do it well. We obtained -3, 0 and 0 so we have hedge both Gamma and Vega exposure. But we have always delta exposure -3.
long_randomchoice = [[3], [0], [0]] # So we creat a new position to neutralize the delta by buying 3 shares of randomchoice.
print(np.round(np.dot(np.round(greeks, 2), w) + portfolio_greeks + long_randomchoice)) # Here we check that we have neutralize Delta, Gamma and Vega. It is good (0 ,0 , 0).

-451.0332970484993
-14.48653713404089
-702.1382445098338
0.5144476408678863
0.01652331413605368
0.8008574218687055
0.3893998125297834
0.012506958756959998
0.6061913889091888
[[ 145.23809524   -2.38095238]
 [-190.47619048    4.76190476]]
[[432.23933492]
 [584.17504356]]
[[-0.]
 [-0.]]
[[-3.]
 [-0.]
 [-0.]]
[[ 0.]
 [-0.]
 [-0.]]
